name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
     - name: send telegram message on push
       uses: appleboy/telegram-action@master
       with:
          to: 5231529781 
          token: 8127490649:AAH70xruUtBQHB2c2GGmgH_J-AJBue5kzdg
          message: Пацер и Михайлова
